manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: kot149
      url-base: https://github.com/kot149
    - name: ssbb
      url-base: https://github.com/ssbb
    - name: caksoylar
      url-base: https://github.com/caksoylar
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: eb99b4ede06bc01674ce16217ebbad40bc11ec50 # main
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: kot149
      revision: b9511f92e4212697e4fd8747c9837c4b9dfc105a # main
      path: modules/zmk-pmw3610-driver
    - name: zmk-listeners
      remote: ssbb
      revision: c240ceaf353d3138bea7695eef17049b7ade995b # v1
      path: modules/zmk-listeners
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: c12cf5cb28e44809d9f07e895ffcf10c0026d3dd # main
      path: modules/zmk-rgbled-widget
    - name: zmk-layout-shift
      remote: kot149
      revision: 31871b0507751aab762db57d6a0ec3665252701e # v1
      path: modules/zmk-layout-shift
  self:
    path: config
