manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: inorichi
      url-base: https://github.com/inorichi
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: inorichi
      revision: main
    # Mouse gesture disabled for stable auto mouse layer
    # - name: zmk-mouse-gesture
    #   remote: kot149
    #   revision: v1
  self:
    path: config
