manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: kumamuk-git
      url-base: https://github.com/kumamuk-git
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: kumamuk-git
      revision: main
    # Mouse gesture disabled for stable auto mouse layer
    # - name: zmk-mouse-gesture
    #   remote: kot149
    #   revision: v1
    - name: zmk-auto-layer
      remote: urob
      revision: main
  self:
    path: config
